INSERT INTO Bar (bar_name, city_id) VALUES ('Dean, Hernandez and Harding', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Cunningham, Bass and Carlson', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Lopez Inc', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Lopez Ltd', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Williams, Kelley and Little', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Mcbride-Cole', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Baker-Herman', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Hall LLC', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Rodriguez, Mcbride and Morris', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Weber, Phelps and Nelson', 1);
INSERT INTO Bar (bar_name, city_id) VALUES ('Jones-Martin', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Lin, Farrell and Walker', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Bautista-Jones', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Carter, Adams and Bray', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Hill, Lucero and Larsen', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Ruiz PLC', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Burns and Sons', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Wade, Dixon and Carrillo', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Proctor-Davis', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Perez, Werner and Thomas', 2);
INSERT INTO Bar (bar_name, city_id) VALUES ('Moore PLC', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Barrett-Mitchell', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Johnson and Sons', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Martin, Gibson and Chavez', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Hinton, Walsh and Hall', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Brown Ltd', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Pollard Ltd', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Mitchell-Davenport', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Turner, Sullivan and Allen', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Jones, Gibson and Walsh', 3);
INSERT INTO Bar (bar_name, city_id) VALUES ('Duncan, Pham and Rose', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Flores Inc', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Heath Group', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Burnett and Sons', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Johnson, Brown and Ochoa', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Evans-Roach', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Calderon, Harris and Calhoun', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Jones, Higgins and Watson', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Smith-Taylor', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Miller, Strong and Evans', 4);
INSERT INTO Bar (bar_name, city_id) VALUES ('Burns-Miles', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Campbell, Johnson and Diaz', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Patterson-Dunn', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Mendez, Cameron and Martin', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Wright-Gomez', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Ryan, Thomas and Wells', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Yang, Tucker and Clark', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Miller PLC', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Dickson-Cordova', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Reynolds and Sons', 5);
INSERT INTO Bar (bar_name, city_id) VALUES ('Chaney Group', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Gaines, Conrad and Taylor', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Torres, Jennings and Wiley', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Bishop, Holland and Thompson', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Clark-Johnson', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Elliott-Patterson', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('West PLC', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Wagner-Stanley', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Johnston-Moore', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Roberts, Martin and Gonzalez', 6);
INSERT INTO Bar (bar_name, city_id) VALUES ('Robles Ltd', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Smith and Sons', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Moore and Sons', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Brown-Garza', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Barron, Bennett and Raymond', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Chapman PLC', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Herman, Diaz and Gonzalez', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Ramirez Inc', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Martinez, Forbes and Bradley', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Benitez, Lindsey and Golden', 7);
INSERT INTO Bar (bar_name, city_id) VALUES ('Adkins, Rivera and Patterson', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Trevino Inc', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Pineda, Flowers and Morton', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Cannon and Sons', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Davidson-Lopez', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Roberts PLC', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Johnson and Sons', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Green, Harmon and Jones', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Michael LLC', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Black Group', 8);
INSERT INTO Bar (bar_name, city_id) VALUES ('Anderson, Griffith and Brock', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Fox, Ross and Gutierrez', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Hernandez, Robinson and Dudley', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Alvarado-Hodges', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Fields, Chang and Haley', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Garrison Inc', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Ortiz, Tran and Taylor', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Watkins, Allen and Ryan', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Ochoa, Potts and Barajas', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Baker PLC', 9);
INSERT INTO Bar (bar_name, city_id) VALUES ('Rojas, Hahn and Huang', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Martinez Inc', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Guzman, Gutierrez and Nunez', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Adkins Inc', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Johnson PLC', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Pierce-Hickman', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Alvarado-Morales', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Hurst LLC', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Brown-Marshall', 10);
INSERT INTO Bar (bar_name, city_id) VALUES ('Collins Inc', 10);
